<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "###EXT###"
 *
 * Auto generated by Extension Builder ###DATE###
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => '###EXT###',
    'description' => '###DESC###',
    'category' => 'be',
    'author' => '###AUTHOR###',
    'author_email' => '###EMAIL###',
    'state' => '###STATE###',
    'internal' => '',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '###VERSION###',
    'constraints' => array(
        'depends' => array(
            'extbase' => '7.6.0-7.6.99',
            'fluid' => '7.6.0-7.6.99',
            'typo3' => '7.6.0-7.6.99',
            'php' => '5.6.0-7.0.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);