<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "drc_instagramfeed"
 *
 * Auto generated by Extension Builder 2016-09-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DRC Instagram Feed',
	'description' => 'DRC Instagram Feed. Its will get the images from the instagram acount',
	'category' => 'plugin',
	'author' => 'DRC Systems',
	'author_email' => 'info@drcsystems.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.99-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);