<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "razor"
 *
 * Auto generated by Extension Builder 2014-09-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'razor',
    'description' => 'razor TYPO3 distribution package',
    'category' => 'distribution',
    'author' => 'Raphael Zschorsch',
    'author_email' => 'rafu1987@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '2.0.4',
    'constraints' => array(
        'depends' => array(
            'extbase' => '7.6.0-7.6.99',
            'fluid' => '7.6.0-7.6.99',
            'typo3' => '7.6.0-7.6.99',
            'php' => '5.6.0-7.0.99',
            'dce' => '1.4.0-1.4.99',
            'realurl' => '',
            'metaseo' => '',
            'vhs' => '',
            'pagenotfoundhandling' => '',
            'gridelements' => '',
            'sourceopt' => '',
            'powermail' => '',
            'jh_captcha' => '',
            'static_info_tables' => '',
            'static_info_tables_de' => '',
            'rzcoreupdate' => '',
            'news' => '',
            'razornews' => '',
            'rzpagetreetools' => '',
            'extension_builder' => '7.6.0-7.6.99',
            'realurlclearcache' => '',
            'fancyboxcontent' => '2.0.0-2.0.99',
            'scheduler' => '7.6.0-7.6.99',
            'recycler' => '7.6.0-7.6.99',
            'indexed_search' => '7.6.0-7.6.99',
            'linkvalidator' => '7.6.0-7.6.99',
        ),
        'conflicts' => array(
            'bootstrap_package' => '',
            'introduction' => '',
        ),
        'suggests' => array(

        ),
    ),
    'autoload' => array(
        'psr-4' => array(
            'RZ\\Razor\\' => 'Classes',
        ),
    ),
);
